# Generated by Django 4.1.6 on 2023-02-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_category_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_type',
            field=models.CharField(default='Like', max_length=50),
        ),
    ]
