# Generated by Django 4.1.6 on 2023-02-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_like_like_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='messageClassified',
            field=models.IntegerField(choices=[(1, 'spam'), (0, 'not_spam')], null=True),
        ),
    ]
